### ISSUE TITLE
Error: Cannot find node with name: Detached Window

### ISSUE THREAD

**Issue by orlov-vo** [ykahlon/heap-cleaner#1]
Hi! I can't reduce heap snapshot with your tool :(

Heap snapshot: [Heap-20201006T090550.heapsnapshot.zip](https://github.com/ykahlon/heap-cleaner/files/5331685/Heap-20201006T090550.heapsnapshot.zip)
I took it from the background page of [Extension Reloader](https://chrome.google.com/webstore/detail/extensions-reloader/fimgfedafeadlieiabdeeaodndnlbhid)

```
-> % node --require ts-node/register --max-old-space-size=8192 --stack-size=160000000 src/cleaner.ts ~/Downloads/Heap-20201006T090550.heapsnapshot 
[ '/Users/vlad/Downloads/Heap-20201006T090550.heapsnapshot' ]
reading file - start!
reading file - end!
Building graph - start!
reading nodes - start!
reading nodes - end. Read: 23677 nodes.
reading edges - start!
reading edges - end. Read: 83162 edges.
Building graph - end!
(node:91261) UnhandledPromiseRejectionWarning: Error: Cannot find node with name: Detached Window
    at GraphManager.findNodeByName (/Users/vlad/dev/heap-cleaner/src/graph-manager.ts:290:11)
    at /Users/vlad/dev/heap-cleaner/src/cleaner.ts:14:22
    at Generator.next (<anonymous>)
    at fulfilled (/Users/vlad/dev/heap-cleaner/src/cleaner.ts:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by ykahlon** [comment]
Hi @orlov-vo happy you are using the tool!! It seems that your heap snapshot does not have a detached window and you do not pass a node id to focus on as a parameter. 
If there is a specific node id you would like to focus on you can pass it as the second parameter.
You can find the node id by loading the snapshot into the dev tools memory profiler.

For example, you can execute this command in order to focus on all retainers of Document:
```
node --require ts-node/register --max-old-space-size=8192 --stack-size=160000000 src/cleaner.ts ~/Downloads/Heap-20201006T090550.heapsnapshot 32095
```
